project:
  type: website
  render:
    - index.qmd
    - einfuehrung.qmd
    - theorie.qmd
    - verwandte_methoden.qmd
    - csg.qmd
  resources:
    - demos/
    - tobias-assets/

format:
  html:
    css: styles.css
    theme: default
    toc: true
    toc-depth: 2
    lang: de
    grid:
      body-width: 1500px
      margin-width: 220px
      gutter-width: 1.5rem

website:
  title: "SDF Rendering via Ray Marching"
  navbar: 
    left:
      - href: index.qmd
        text: "Home"

      - href: einfuehrung.qmd
        text: "Einführung"

      - href: theorie.qmd
        text: "Theorie"      

      - href: verwandte_methoden.qmd
        text: "Verwandte Methoden"

      - href: csg.qmd
        text: "CSG"
