project:
  type: website
  render:
    - pages/einfuehrung.qmd
    - pages/theorie.qmd
    - pages/verwandte-methoden.qmd
    - pages/csg.qmd
    - pages/demos.qmd
    - pages/grenzen-artefakte.qmd
  resources:
    - assets/

bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - theme-dark.scss
    css: styles.css
    toc: true
    toc-depth: 2
    lang: de
    grid:
      body-width: 1500px
      margin-width: 220px
      gutter-width: 1.5rem

website:
  title: "SDF Rendering via Ray Marching"
  navbar:
    left:
      - href: pages/einfuehrung.qmd
        text: "Einführung"

      - href: pages/theorie.qmd
        text: "Theorie"

      - href: pages/verwandte-methoden.qmd
        text: "Verwandte Methoden"

      - href: pages/csg.qmd
        text: "CSG"

      - href: pages/grenzen-artefakte.qmd
        text: "Grenzen & Artefakte"

      - href: pages/demos.qmd
        text: "Demos"